### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by katrinleinweber**
See diff ;-) I hope this was not an intentional duplication of `the`. I guessed it was just copied from some template with that typo.

### CODE REVIEW

**Comment by bradymholt** [comment]
Thanks @katrinleinweber !  It looks like the type itself is actually in the Swagger template here: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/ruby/base_object.mustache#L8.  So, the next time we generate the typo would come back 😦 .  But, we can override the template to fix it.  Would you be up for copying the [template file](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/ruby/base_object.mustache) into [this directory](https://github.com/ynab/ynab-sdk-ruby/tree/master/swagger-templates) and then fixing the typo there?  That way the fix will persist next time generate as well. 

Thank you!

**Comment by katrinleinweber** [comment]
I'm guessing https://github.com/swagger-api/swagger-codegen/pull/9019 makes even more sense in the long-run, albeit probably taking longer to trickle down initially, doesn't it?

**Comment by bradymholt** [comment]
@katrinleinweber Yes!  That's probably the best place so we don't have to override the template just to change the typo.  Thanks for submitting that on the original repo!  Are you ok with us closing this PR out and waiting for that change to come down from the Swagger repo?

**Comment by katrinleinweber** [comment]
Sure :-)

**Pull request closed without merging**
